services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: tinycdn
    env_file:
      - .env
    volumes:
      - ./domains.json:/app/domains.json:ro
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - prometheus

  redis:
    image: redis:7.4-alpine
    container_name: tinycdn-redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  prometheus:
    image: prom/prometheus:latest
    container_name: tinycdn-prometheus
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
